### ISSUE TITLE
Consuming 30G when used via noevim coc

### ISSUE THREAD

**Issue by ony** [nix-community/rnix-lsp#33] opened 2021-03-29 14:22 UTC
Hello,

I had two incidents already when with `rnix-lsp` consumed almost all RAM.
It is interesting that in both cases I had in parallel other terminal running `nix repl` while editing `home.nix` (home-manager) with error syntax error.

```nix
# home.nix
let
  # first evaluated yesterday
  rnix-lsp = import "${builtins.fetchTarball https://github.com/nix-community/rnix-lsp/archive/master.tar.gz}";
in {
  # ...
  # Effectively generating ~/.config/nvim/coc-settings.json
    nix = {
      command = "${rnix-lsp}/bin/rnix-lsp";
      filetypes = ["nix"];
    };
}
```

```dmesg
...
Mar 29 15:49:04 ony kernel: Mem-Info:
Mar 29 15:49:04 ony kernel: active_anon:7466684 inactive_anon:441570 isolated_anon:0
                             active_file:949 inactive_file:1626 isolated_file:158
                             unevictable:0 dirty:0 writeback:0 unstable:0
                             slab_reclaimable:54731 slab_unreclaimable:58579
                             mapped:9174 shmem:12085 pagetables:38810 bounce:0
                             free:50700 free_pcp:1207 free_cma:0
..
Mar 29 15:49:04 ony kernel: Tasks state (memory values in pages):
Mar 29 15:49:04 ony kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
...
Mar 29 15:49:04 ony kernel: [  24361]  1000 24361    76923     1754   114688     1148             0 nvim
Mar 29 15:49:04 ony kernel: [  24363]  1000 24363   160515      596  1519616     6984             0 node
...
Mar 29 15:49:04 ony kernel: [  24381]  1000 24381 16812507  7618497 117530624  7033451             0 rnix-lsp
Mar 29 15:49:04 ony kernel: [  14255]  1000 14255   145768        0   368640    30960             0 nix
Mar 29 15:49:04 ony kernel: [  14868]     0 14868   114793        1   122880     1369             0 nix-daemon
...
Mar 29 15:49:04 ony kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1000.slice/session-5.scope,task=rnix-lsp,pid=24381,uid=1000
Mar 29 15:49:04 ony kernel: Out of memory: Killed process 24381 (rnix-lsp) total-vm:67250028kB, anon-rss:30473988kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:114776kB oom_score_adj:0
Mar 29 15:49:04 ony kernel: oom_reaper: reaped process 24381 (rnix-lsp), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

**Comment by Ma27** [comment] 2021-07-05 07:46
There's a certain chance that this got fixed in #37, but I really want to look at this before getting a 0.2.0 out.

**Comment by ony** [comment] 2021-07-19 06:33
I was not able to reproduce issue for past 2 days (effective run-time ~7 minutes). I tried keeping `all-packages.nix` open and tried putting `rec` and do some auto-completion. During open it was taking ~16M and after completion ~32M with grow to ~33M over time, but later went down to ~31.7M. Virtual memory/space is ~160M.  
In first hour I tried latest commit. But after seeing no issues switched to 6c12d7fd20e3330669ba1a845b78694d600283a3 to confirm that I still can reproduce on original commit for report.
Note that when I was reporting this issue I was using stable Nix and now I use Flakes (without `NIX_PATH` injection, but with registry pin for `nixpkgs`). As well I was on NixOS `20.09` and now on `21.05`.

**Comment by Ma27** [comment] 2021-07-20 15:56
THanks a lot for reporting back! In case you stumble upon this again, please let us know! I'll leave this open for another two weeks to see if you, me or somebody else can reproduce this.

**Comment by fufexan** [comment] 2021-07-25 17:39
I've had this same problem, but it seems like the incremental expression-updates commit has fixed it. Thanks!

**Comment by Ma27** [comment] 2021-07-26 17:25
In case somebody *still* stumbles upon the issue on a recent `master` of `rnix-lsp`: it would be really awesome if you could share a coredump of the process then, because I'd really like to look at the memory itself then.

One (hacky, I guess?) way to do this is to kill `rnix-lsp` via `kill -11` (to "simulate" a SIGSEGV) which usually causes the creation of a coredump.

**Comment by Ma27** [comment] 2021-07-29 12:13
Damn it, I just experienced this again :/ Unfortunately my kernel was faster with OOMing rnix-lsp than I could `kill -11` it to get a coredump. Luckily I'm write rather much Nix code currently, so hopefully I'll be faster next time.

**Comment by ony** [comment] 2021-07-31 16:07
Any chance to instrument some memory debugging into `rnix-lsp` itself?
E.g. force memory limit to 4GB and handle `ENOMEM` with `SIGABRT`-ing self.

@Ma27 , any chance that it happened for you on Nix 2.3.x?

**Comment by Ma27** [comment] 2021-07-31 16:09
>  E.g. force memory limit to 4GB and handle ENOMEM with SIGABRT-ing self.

Good idea :) 

> any chance that it happened for you on Nix 2.3.x?

Nope, Nix 2.4

**Comment by fufexan** [comment] 2021-08-16 14:29
> In case somebody _still_ stumbles upon the issue on a recent `master` of `rnix-lsp`: it would be really awesome if you could share a coredump of the process then, because I'd really like to look at the memory itself then.
> 
> One (hacky, I guess?) way to do this is to kill `rnix-lsp` via `kill -11` (to "simulate" a SIGSEGV) which usually causes the creation of a coredump.

@Ma27 I have finally managed to catch it before freezing my PC. Here's a screenshot of the coredump as my terminal somehow got messed up and I couldn't copy the text from it.
![rnix-dump](https://user-images.githubusercontent.com/36706276/129579717-5a5d148f-e575-4ca4-bd2e-78bc922f4656.png)

The circumstances are: I was editing a `fetchFromGitHub` call that used `lib.fakeHash` and modifying the `sha256` to the proper hash. As soon as I pasted the hash, `rnix-lsp` (or `kak-lsp`? not sure) started eating memory and I managed to kill it with `doas pkill -11 rnix-lsp` which I had prepared beforehand in a terminal nearby.

I could send the file if it helps.

**Comment by Ma27** [comment] 2021-08-16 14:35
> I could send the file if it helps.

Can you still access the core file? That one would be quite helpful! :)

**Comment by fufexan** [comment] 2021-08-16 14:39
I'm not sure whether you mean the coredump file (I don't know where it's located), but this is the nix file that caused it to leak. https://gist.github.com/fufexan/61244c3949ec631d6f1483bbbc682b61

**Comment by Ma27** [comment] 2021-08-16 14:41
@fufexan are you on NixOS? In that case `coredumpctl gdb` should give you the answer (the `Storage`-property).

**Comment by fufexan** [comment] 2021-08-16 14:43
I have found it. https://gofile.io/d/WJElaV

**Comment by Ma27** [comment] 2021-08-16 16:21
@fufexan one last question: do you have a custom overlay for your `rnix-lsp`? Or from which nixpkgs revision (`nixos-version` should help) did you build it from?

**Comment by fufexan** [comment] 2021-08-16 17:16
@Ma27 I'm using the flake in this repo along with `nixpkgs-unstable` (21.11.20210729.dd98b10).

**Comment by Ma27** [comment] 2021-08-31 21:46
@ony @fufexan there's now #49 which contains a few dependency updates (including a fix for crossbeam which resolves a severe memory leak in their code). Since I still cannot reproduce the bug reliably (although I get bitten by it occasionally), this is only a theory, unfortunately.

In order to find out whether this is an actual fix, it'd be really awesome if you could also test this PR :)

**Comment by fufexan** [comment] 2021-09-01 11:20
@Ma27 tried building it, but it failed. Here's the build log https://gist.github.com/fufexan/f82d75bae6cfcfb95f984bb92b07ebc4.

**Comment by Ma27** [comment] 2021-09-01 11:39
You'll need at least cargo+rustc 1.52 (should be on available nixos 21.05).

**Comment by fufexan** [comment] 2021-09-01 11:41
I'm on unstable from a week ago, I think it should work even with that.

**Comment by Ma27** [comment] 2021-09-01 11:49
Your log says `[naersk] cargo_version (read): 1.47.0` though. Not sure why, though. Locally, it appears to use the correct versions for the build.

**Comment by fufexan** [comment] 2021-09-01 14:27
Manually overriding `rnix-lsp`'s `naersk` input with an updated one made it work.

**Comment by fufexan** [comment] 2021-09-02 09:56
I use Kakoune, Neovim and Emacs :smile: 
So far I've managed to trigger the leak with `kak` and `nvim`, as I haven't used `emacs` extensively.
My configs are [here](https://github.com/fufexan/dotfiles/tree/main/home/editors).

**Comment by Ma27** [comment] 2021-09-19 13:14
-> https://github.com/nix-community/rnix-parser/pull/31/files

Big thanks to @fufexan for helping me to reproduce this! Feel free to remind me on the next in-person NixCon (or something similar) that I owe you a beverage of your choice :)

**Closed** 2021-09-23 12:14 UTC
Labels: bug
